"""File layer definitions for data pipeline organization.

This module defines the different layers in a data pipeline and provides
mapping between layer enums and their corresponding directory names.
"""

from enum import StrEnum
from typing import Final


class FileLayer(StrEnum):
    """Enumeration of data pipeline layers.

    This enum defines the different layers in a typical data pipeline,
    following a structured approach where data flows through various
    stages of processing and transformation.

    The file layers concept is inspired by Kedro; see an accompanying
    blog post [here](https://towardsdatascience.com/the-importance-of-layered-thinking-in-data-engineering-a09f685edc71/).

    Each layer represents a specific stage in the data processing workflow:
    - RAW: Unprocessed source data as received; should be immutable
    - INTERMEDIATE: Typed data that is still very close to the raw source
    - PRIMARY: Data after model-specific, simple transformations
    - FEATURE: Engineered features for model training/inference
    - MODEL_INPUT: Data for model consumption, also called 'master tables'
    - MODELS: Trained models, their artefacts, and their configurations
    - MODEL_OUTPUT: Generated by model runs
    - REPORTING: Whatever is needed for reporting/visualization
    """

    RAW = "raw"
    INTERMEDIATE = "intermediate"
    PRIMARY = "primary"
    FEATURE = "feature"
    MODEL_INPUT = "model_input"
    MODELS = "models"
    MODEL_OUTPUT = "model_output"
    REPORTING = "reporting"


# Mapping between file layers and their corresponding directory names
file_layer_mapping: Final[dict[FileLayer, str]] = {
    FileLayer.RAW: "01_raw",
    FileLayer.INTERMEDIATE: "02_intermediate",
    FileLayer.PRIMARY: "03_primary",
    FileLayer.FEATURE: "04_feature",
    FileLayer.MODEL_INPUT: "05_model_input",
    FileLayer.MODELS: "06_models",
    FileLayer.MODEL_OUTPUT: "07_model_output",
    FileLayer.REPORTING: "08_reporting",
}
